name: "Bundle Size Check"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

env:
  CI_REPO_OWNER: ${{ github.repository_owner }}
  CI_REPO_NAME: next-template
  CI_COMMIT_SHA: ${{ github.sha }}
  CI_BRANCH: main
  BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install
        run: pnpm install

      - name: Restore next build
        uses: actions/cache@v4
        id: restore-build-cache
        env:
          cache-name: cache-next-build
        with:
          path: .next/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build next.js app
        run: ./node_modules/.bin/next build

      - name: Analyze bundle
        run: pnpm bundlewatch
